from typing import Dict, Any
from app.nodes.base import BaseNodeExecutor, render_template


class ButtonsNodeExecutor(BaseNodeExecutor):

    def execute(
        self,
        node_config: Dict[str, Any],
        state: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Execute a Buttons node.

        Supports both:

            ["Option 1", "Option 2"]

        and:

            [
                {
                    "label": "Option 1",
                    "value": "option_1",
                    "next_node": "node-id"
                },
                {
                    "label": "Option 2",
                    "value": "option_2",
                    "next_node": "node-id"
                }
            ]

        The button response is APPENDED to any response that
        was already generated by previous nodes.
        """

        # =========================================================
        # GET NODE CONFIG
        # =========================================================

        config = (
            node_config.get("config")
            or node_config.get("data")
            or node_config
            or {}
        )

        # =========================================================
        # GET BUTTON MESSAGE
        # =========================================================

        message = (
            config.get("text")
            or config.get("message")
            or node_config.get("message")
            or node_config.get("text")
            or ""
        )

        message = str(message).strip()

        # Render variables if the button message contains them
        message = render_template(
            message,
            state.get("variables", {})
        )

        # =========================================================
        # GET OPTIONS
        # =========================================================

        # Prefer the node-level "options" list (structured
        # label/value/next_node objects) over "config.options",
        # which is frequently just a list of plain label strings
        # saved by the flow builder UI and carries no next_node
        # routing info.
        options = (
            node_config.get("options")
            or config.get("options")
            or []
        )

        if not isinstance(options, list):
            options = []

        # =========================================================
        # NORMALIZE OPTIONS
        # =========================================================

        normalized_options = []

        for index, option in enumerate(options):

            # -----------------------------------------------------
            # Dictionary option
            # -----------------------------------------------------

            if isinstance(option, dict):

                label = (
                    option.get("label")
                    or option.get("value")
                    or f"Option {index + 1}"
                )

                value = (
                    option.get("value")
                    or str(label)
                    .lower()
                    .strip()
                    .replace(" ", "_")
                )

                next_node = option.get("next_node")

            # -----------------------------------------------------
            # String option
            # -----------------------------------------------------

            elif isinstance(option, str):

                label = option.strip()

                value = (
                    option
                    .lower()
                    .strip()
                    .replace(" ", "_")
                )

                next_node = None

            # -----------------------------------------------------
            # Unknown option type
            # -----------------------------------------------------

            else:

                label = f"Option {index + 1}"

                value = (
                    str(label)
                    .lower()
                    .strip()
                    .replace(" ", "_")
                )

                next_node = None

            normalized_options.append({
                "label": str(label),
                "value": str(value),
                "next_node": next_node,
            })

        # =========================================================
        # BUILD BUTTON LIST
        # =========================================================

        formatted_options = "\n".join(
            f"{index + 1}. {option['label']}"
            for index, option in enumerate(normalized_options)
        )

        # =========================================================
        # BUILD BUTTON RESPONSE
        # =========================================================

        if message and formatted_options:

            button_response = (
                f"{message}\n\n"
                f"{formatted_options}"
            )

        elif formatted_options:

            button_response = formatted_options

        else:

            button_response = message

        # =========================================================
        # COPY STATE
        # =========================================================

        updated_state = dict(state)

        # =========================================================
        # IMPORTANT:
        #
        # DO NOT overwrite an existing response.
        #
        # Example:
        #
        # Message node:
        #   "Welcome to Thriftify!"
        #
        # Buttons node:
        #   "Choose an option..."
        #
        # Final response:
        #
        #   Welcome to Thriftify!
        #
        #   Choose an option...
        #   1. Place Order
        #   2. Check Discount
        # =========================================================

        existing_response = str(
            updated_state.get("response") or ""
        ).strip()

        if existing_response and button_response:

            updated_state["response"] = (
                f"{existing_response}\n\n"
                f"{button_response}"
            )

        elif button_response:

            updated_state["response"] = button_response

        else:

            updated_state["response"] = existing_response

        # =========================================================
        # WAIT FOR USER INPUT
        # =========================================================

        updated_state["status"] = "waiting_for_input"

        # =========================================================
        # STORE BUTTON OPTIONS
        # =========================================================

        updated_state["button_options"] = normalized_options

        # =========================================================
        # KEEP CURRENT NODE
        #
        # This is important because the next user message
        # needs to be interpreted as a button selection.
        # =========================================================

        updated_state["current_node"] = node_config.get("id")

        return updated_state